#!/usr/bin/env python

"""This is the ui code for the explorer tool"""

# python
import sys

# PySide
from PySide import QtGui, QtCore

__author__ = "Emre Tekinalp"
__copyright__ = "Copyright 2018, Gravity of Explosion"
__credits__ = ["Emre Tekinalp"]
__license__ = "MIT"
__version__ = "1.0.0"
__maintainer__ = "Emre Tekinalp"
__email__ = "e.tekinalp@icloud.com"
__status__ = "Unfinished"


class ExplorerUi(QtGui.QDialog):
    """Show explorer gui inside maya"""

    def __init__(self, parent=None):
        """Initialize ExplorerUi class"""
        QtGui.QDialog.__init__(self, parent)
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        main_layout = QtGui.QVBoxLayout()
        self.slider = QtGui.QSlider()
        self.slider.setMinimum(0)
        self.slider.setMaximum(200)
        self.slider.setValue(50)
        self.color = QtGui.QColor(0, 0, 0, self.slider.value())
        self.slider.valueChanged.connect(self.slider_value)
        main_layout.addWidget(self.slider)

        self.close_btn = QtGui.QPushButton('Close')
        self.close_btn.clicked.connect(self.close)
        main_layout.addWidget(self.close_btn)

        self.setLayout(main_layout)
        self.resize(400, 400)

    def slider_value(self):
        self.color.setAlpha(self.slider.value())
        self.repaint()

    def paintEvent(self, event):
        super(ExplorerUi, self).paintEvent(event)
        painter = QtGui.QPainter()
        painter.begin(self)
        painter.fillRect(0, 0, self.width(), self.height(), self.color)
        painter.setCompositionMode(QtGui.QPainter.CompositionMode_Source)
        painter.end()


def main():
    app = QtGui.QApplication(sys.argv)
    w = ExplorerUi()
    w.show()
    app.exec_()

if __name__ == '__main__':
    main()
