# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\GitHub\Qt\src\python\table_widget\tableWidget.ui'
#
# Created: Sun Mar 19 19:30:18 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(385, 505)
        MainWindow.setStyleSheet("background-color: rgb(22, 22, 22);")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.createBtn = QtGui.QPushButton(self.centralwidget)
        self.createBtn.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(208, 208, 208);")
        self.createBtn.setObjectName("createBtn")
        self.verticalLayout.addWidget(self.createBtn)
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"alternate-background-color: rgb(48, 48, 48);\n"
"selection-background-color: rgba(255, 0, 0, 0);\n"
"selection-color: rgb(255, 170, 0);")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.tableWidgetEdit = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetEdit.sizePolicy().hasHeightForWidth())
        self.tableWidgetEdit.setSizePolicy(sizePolicy)
        self.tableWidgetEdit.setStyleSheet("background-color: rgb(33, 33, 33);\n"
"color: rgb(222, 222, 222);\n"
"alternate-background-color: rgb(40, 40, 40);")
        self.tableWidgetEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetEdit.setAlternatingRowColors(True)
        self.tableWidgetEdit.setObjectName("tableWidgetEdit")
        self.tableWidgetEdit.setColumnCount(2)
        self.tableWidgetEdit.setRowCount(7)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableWidgetEdit.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEdit.setItem(6, 1, item)
        self.tableWidgetEdit.horizontalHeader().setVisible(False)
        self.tableWidgetEdit.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetEdit.verticalHeader().setVisible(False)
        self.tableWidgetEdit.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidgetEdit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.createBtn.setText(QtGui.QApplication.translate("MainWindow", "create", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "driver", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "start frame", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "end frame", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "bakes", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "skin mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.verticalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "sim mesh", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.tableWidgetEdit.isSortingEnabled()
        self.tableWidgetEdit.setSortingEnabled(False)
        self.tableWidgetEdit.item(0, 0).setText(QtGui.QApplication.translate("MainWindow", "name", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.item(1, 0).setText(QtGui.QApplication.translate("MainWindow", "driver", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.item(2, 0).setText(QtGui.QApplication.translate("MainWindow", "start frame", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.item(3, 0).setText(QtGui.QApplication.translate("MainWindow", "end frame", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.item(4, 0).setText(QtGui.QApplication.translate("MainWindow", "bakes", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.item(5, 0).setText(QtGui.QApplication.translate("MainWindow", "skin mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.item(6, 0).setText(QtGui.QApplication.translate("MainWindow", "sim mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEdit.setSortingEnabled(__sortingEnabled)

