# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\GitHub\Qt\src\python\audio_flashcard\audioFlashcard.ui'
#
# Created: Wed Mar 29 22:40:32 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(440, 516)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(30, 30, 30);\n"
"color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(40, 40, 40);")
        MainWindow.setAnimated(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setObjectName("stackedWidget")
        self.title_page = QtGui.QWidget()
        self.title_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_page.setObjectName("title_page")
        self.verticalLayout = QtGui.QVBoxLayout(self.title_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nameLab = QtGui.QLabel(self.title_page)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.nameLab.setFont(font)
        self.nameLab.setObjectName("nameLab")
        self.horizontalLayout_4.addWidget(self.nameLab)
        self.nameLed = QtGui.QLineEdit(self.title_page)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.nameLed.setFont(font)
        self.nameLed.setFrame(False)
        self.nameLed.setObjectName("nameLed")
        self.horizontalLayout_4.addWidget(self.nameLed)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 22, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.titleLab = QtGui.QLabel(self.title_page)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.titleLab.setFont(font)
        self.titleLab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.titleLab.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLab.setObjectName("titleLab")
        self.verticalLayout.addWidget(self.titleLab)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setContentsMargins(10, 20, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.englishLab = QtGui.QLabel(self.title_page)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.englishLab.setFont(font)
        self.englishLab.setStyleSheet("color: rgb(183, 10, 70);")
        self.englishLab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.englishLab.setAlignment(QtCore.Qt.AlignCenter)
        self.englishLab.setObjectName("englishLab")
        self.horizontalLayout_2.addWidget(self.englishLab)
        self.japaneseLab = QtGui.QLabel(self.title_page)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.japaneseLab.setFont(font)
        self.japaneseLab.setStyleSheet("color: rgb(183, 10, 70);")
        self.japaneseLab.setFrameShape(QtGui.QFrame.StyledPanel)
        self.japaneseLab.setAlignment(QtCore.Qt.AlignCenter)
        self.japaneseLab.setObjectName("japaneseLab")
        self.horizontalLayout_2.addWidget(self.japaneseLab)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 165, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.title_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.previousBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousBtn.sizePolicy().hasHeightForWidth())
        self.previousBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.previousBtn.setFont(font)
        self.previousBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.previousBtn.setStyleSheet("QPushButton{border: none;}\n"
"QPushButton:hover{\n"
"border: none;\n"
"color: rgb(255, 60, 60);\n"
"}\n"
"QPushButton:pressed{\n"
"border: none;\n"
"color: rgb(255, 60, 60);\n"
"font-size: 16pt\n"
"}")
        self.previousBtn.setObjectName("previousBtn")
        self.horizontalLayout_3.addWidget(self.previousBtn)
        self.pageLab = QtGui.QLabel(self.centralwidget)
        self.pageLab.setStyleSheet("color: rgb(255, 204, 0);")
        self.pageLab.setObjectName("pageLab")
        self.horizontalLayout_3.addWidget(self.pageLab)
        self.nextBtn = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextBtn.sizePolicy().hasHeightForWidth())
        self.nextBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.nextBtn.setFont(font)
        self.nextBtn.setStyleSheet("QPushButton{border: none;}\n"
"QPushButton:hover{\n"
"border: none;\n"
"color: rgb(60, 255, 60);\n"
"}\n"
"QPushButton:pressed{\n"
"border: none;\n"
"color: rgb(60, 255, 60);\n"
"font-size: 16pt\n"
"}")
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_3.addWidget(self.nextBtn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setObjectName("actionOptions")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLab.setText(QtGui.QApplication.translate("MainWindow", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.nameLed.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Please specify your name", None, QtGui.QApplication.UnicodeUTF8))
        self.titleLab.setText(QtGui.QApplication.translate("MainWindow", "My Vocabulary Book", None, QtGui.QApplication.UnicodeUTF8))
        self.englishLab.setText(QtGui.QApplication.translate("MainWindow", "english", None, QtGui.QApplication.UnicodeUTF8))
        self.japaneseLab.setText(QtGui.QApplication.translate("MainWindow", "japanese", None, QtGui.QApplication.UnicodeUTF8))
        self.previousBtn.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pageLab.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.nextBtn.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))

